synccc

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -157,10 +157,21 @@ jobs:
             echo "APK installation failed."
             exit 1
           fi
-      -name: start appium
+
+      - name: Start Appium
         run: |
-         npx appium --log-level error &
-         sleep 10 # Wait for Appium to start
-         
+          npx appium --log-level error &
+          sleep 10 # Wait for Appium to start
+
+      - name: Verify Appium is Running
+        run: |
+          curl http://localhost:4723/wd/hub/status
+          if [ $? -eq 0 ]; then
+            echo "Appium is running."
+          else
+            echo "Appium failed to start."
+            exit 1
+          fi
+
       - name: Run Tests
         run: npm run test:ci
