asasa

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,8 +42,7 @@ jobs:
           rm android-sdk.zip
 
       - name: Verify sdkmanager is in PATH
-        run: |
-          which sdkmanager
+        run: which sdkmanager
 
       - name: Update SDK Repositories
         run: |
@@ -53,14 +52,20 @@ jobs:
 
       - name: Install Required SDK Components
         run: |
-          sdkmanager --install "system-images;android-30;google_apis_playstore;x86" || exit 1
-          sdkmanager --install "emulator" || exit 1
-          sdkmanager --install "platform-tools" || exit 1
-          sdkmanager --install "platforms;android-30" || exit 1
+          sdkmanager --install "platforms;android-30" || { echo "Failed to install platforms"; exit 1; }
+          sdkmanager --install "emulator" || { echo "Failed to install emulator"; exit 1; }
+          sdkmanager --install "platform-tools" || { echo "Failed to install platform-tools"; exit 1; }
+          sdkmanager --install "system-images;android-30;google_apis_playstore;x86" || { echo "Failed to install system-images"; exit 1; }
 
       - name: Verify SDK Setup
         run: |
-          ls -la $ANDROID_HOME/platforms
+          echo "Checking if platforms directory exists..."
+          if [ -d "$ANDROID_HOME/platforms" ]; then
+            echo "Platforms directory found."
+          else
+            echo "Platforms directory not found."
+            exit 1
+          fi
 
       - name: Verify emulator and adb are in PATH
         run: |
@@ -87,8 +92,7 @@ jobs:
           curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
 
       - name: Install APK on Emulator
-        run: |
-          adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk
+        run: adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk
 
       - name: Start Appium Server
         run: |
@@ -104,8 +108,7 @@ jobs:
           done
 
       - name: Run WebDriverIO Tests
-        run: |
-          npx wdio run ./wdio.ci.conf.js
+        run: npx wdio run ./wdio.ci.conf.js
 
       - name: Force Stop Emulator
         run: |
