sss

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,8 +76,8 @@ jobs:
 
       - name: Install system-images
         run: |
-          echo "Installing system-images;android-30;google_apis_playstore;x86..."
-          sdkmanager --install "system-images;android-30;google_apis_playstore;x86" || { echo "Failed to install system-images"; exit 1; }
+          echo "Installing system-images;android-30;default;arm64-v8a..."
+          sdkmanager --install "system-images;android-30;default;arm64-v8a" || { echo "Failed to install system-images"; exit 1; }
           echo "All SDK components installed successfully."
           sleep 10
 
@@ -127,7 +127,7 @@ jobs:
 
       - name: Create and Start Emulator
         run: |
-          echo no | avdmanager create avd --force -n test --abi "google_apis_playstore/x86" --package "system-images;android-30;google_apis_playstore;x86" --device "Nexus 6"
+          echo no | avdmanager create avd --force -n test --abi "default/arm64-v8a" --package "system-images;android-30;default;arm64-v8a" --device "Nexus 6"
           emulator -avd test -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot -memory 2048 -cores 2 &
           adb wait-for-device
           adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
